Implement broadcasting
multiscale/muscle3 pull request #117
Opened 2022-10-11 14:55 UTC by maarten-ic

Allow multiple conduits connected to a single output port. The only limitation is that the multiplicity of all connected peers must be the same (to avoid interference with vector port functionality).

2022-10-13 09:00 UTC, maarten-ic reviewed
Rename broadcast to multicast

2022-11-15 11:18 UTC, LourensVeen requested changes
Nice job! This is looking good overall, but that test bugs me a bit. Could that be fixed?

2022-11-21 08:37 UTC, maarten-ic commented on integration_test/test_multicast_cpp.py
> +if __name__ == "__main__":
Fixed with #134 😄

2022-11-21 19:11 UTC, LourensVeen commented
Codacy is still complaining, but then it's always complaining, so I'm going to merge this because it's a great new addition to MUSCLE3. Thanks, great work!

2022-11-21 19:11 UTC, merged